version: '3.8'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  
    environment:
      - MONGO_URI=mongodb://mongodb:27017/users_db
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data:
